name: 打包应用并上传腾讯云

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        uses: actions/checkout@master

      - name: 安装node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install pnpm
        run: npm install -g pnpm

      # 安装依赖
      - name: 安装依赖
        run: pnpm install

      # 打包
      - name: 打包
        run: pnpm run build

      - name: List files
        run: ls -a

      - name: Compress files to ZIP
        run: |
                zip -r deploy.zip .nuxt .output package.json pm2.config.cjs

      - name: Copy ZIP to Tencent Cloud Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: "./deploy.zip"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/projects/examApp/'

      - name: unzip files
        run: |
          unzip -o deploy.zip -d /www/wwwroot/projects/examApp/
          rm deploy.zip

      - name: List files
        run: ls -a